### ISSUE TITLE
Calcolo quantità articolo "trasporto al piano senza ascensore" nel csv

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#101]
Come da oggetto, quando c'è una consegna al piano senza ascensore, all'interno degli articoli di un ordine, puoi trovare:
Trasporto al piano senza ascensore (massimo al 1° piano) - Collo pesante
Trasporto al piano senza ascensore - Collo leggero
Trasporto al piano senza ascensore - Collo medio

In base al numero di colli e al numero di piani, ogni articolo di questi può avere una quantità differente.
Es. 4 colli medi al 2 piano senza ascensore, troverai 8 unità di Trasporto al piano senza ascensore - Collo medio (4 x 2 piani)-

Mi interessa sapere, insieme al calcolo del peso, quante unità ci sono di questi articoli all'interno degli ordini inclusi nel csv, possibilmente divisi tra le tre tipologie.

Mi serve per capire a colpo d'occhio, avendo questo dato e anche il peso della merce, se è il caso di mandare un aiutante all'autista.

**Comment by LukeSavefrogs** [comment]
Ok, vorrei capire un attimo le priorità:
 
1. Questo controllo si può fare senza l'ausilio del programma o questo issue è sintomo di un disagio?

    - [ ] Possibile manualmente
    - [ ] Impossibile manualmente dopo l'avvento del programma ma possibile in precedenza
    - [ ] Mai stato possibile, per questo sarebbe comodo averla come funzione nel programma

1. Tempo stimato di esecuzione dell'attività (_manualmente_)?

**Comment by LukeSavefrogs** [comment]
Chiuso come duplicato dell'issue #134
