### ISSUE TITLE
Se Cliente/Fornitore, kml non fa segnaposto

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#112]
Come da oggetto, non ha fatto il segnaposto ordine ad un cliente che è anche fornitore.
Il segnaposto generico vuoto invece sì.

**Comment by LukeSavefrogs** [comment]
Come è possibile avere un cliente che sia anche fornitore? 

Da Easyfatt cosa è necessario fare perchè succeda?

**Comment by lasorgentenet** [comment]
Può succedere, quindi ha il flag su entrambe le caselle cliente e fornitore.
Questa è una cantina di vini che sta a Frascati, ad esempio.
Fornitore perché gli compriamo il vino, cliente perché ci hanno comprato due pedane di acqua.

Niente di che, ho esportato il kml e non mi ha messo il segnaposto flaggato anche se c'era l'ordine.

**Comment by lasorgentenet** [comment]
Funziona!
