### ISSUE TITLE
Esportazione csv per zone o globale

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#16]
Vorremmo fare degli export per RouteXL che siano parziali sulle zone che vogliamo servire il giorno successivo.
Potremmo usare uno dei campi Extra del gestionale, ma c'è il solito problema: ad un cliente che ha più indirizzi su diverse zone possiamo assegnare soltanto un valore.

Idea di Thomas: fare in modo che l'applicazione legga i CAP di destinazione di ogni indirizzo, e ci permetta di scegliere se fare un csv per RouteXL che sia comprensivo di tutti gli indirizzi dell'XML (così come fa ora) o soltanto di una o più zone.

Per riuscire a far questo, potremmo assegnare una lettera per ogni zona.
Es. zona che serviamo a Roma il lunedì lettera A, zona che serviamo a Roma il martedì lettera B ecc. 
Chiaramente dobbiamo darti un elenco per farti sapere quali CAP comprenda ogni lettera.

**Comment by lasorgentenet** [comment]
Ci abbiamo pensato bene. Non ci è molto utile, almeno al momento.
Meglio riuscire ad avere una visuale totale veloce per Earth, e poi per Route ci pensiamo noi manualmente a selezionare i clienti che ci interessano per un giro di consegne.
Oggi abbiamo fatto un ulteriore test, e Route non è così bravo quando gli chiedi di fare due giri diversi in una stessa zona.

**Comment by LukeSavefrogs** [comment]
> Oggi abbiamo fatto un ulteriore test, e Route non è così bravo quando gli chiedi di fare due giri diversi in una stessa zona.

Sarei interessato a questo... Potresti mandarmi privatamente (mail o wa) un **esempio** che replichi quel funzionamento che tu dici non va bene?

**Comment by lasorgentenet** [comment]
Si tratta di un suo limite. Fa il miglior giro con le bende sugli occhi, per farti capire. Se la zona è ampia, invece di far sì che un camion faccia una metà e l'altro l'altra metà, fa passare entrambi sull'intera zona, facendo clienti diversi ovviamente. Non ci risulta ottimale, per il discorso traffico ecc. che lui non è in grado di prevedere.
