### ISSUE TITLE
Convertitore veloce da XML gestionale a KML per Earth

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#17]
Niente da aggiungere. Questo ci permette di avere una mappa completa più volte nell'arco della mattinata ovviando all'inserimento manuale.

**Comment by lasorgentenet** [comment]
Ti diamo qualche altra indicazione:

- sintassi nome segnaposto: denominazione cliente - codice cliente - vincolo orario (Extra1) e l'indirizzo solo nel caso in cui lo abbia pescato da una diversa destinazione
- stile, colore, icona segnaposti, se possibile la stessa del kmz che già hai
- sempre se possibile, che si "leghi" ad un altro kmz che abbia già di base i poligoni con le zone colorate, i CAP ecc. (questo dovrei provvedertelo)

**Comment by LukeSavefrogs** [comment]
Non dovrebbe essere invece un problema creare un KML a partire dai **soli indirizzi di residenza**.

Rimane comunque il problema che in questo caso non verrebbero tenuti in considerazione **indirizzi aggiuntivi** (es. nel caso di un indirizzo di consegna diverso da indirizzo di residenza).

![image](https://user-images.githubusercontent.com/33452387/217306679-7c8e36d8-434d-43bc-b138-39a4246872c4.png)

--- 
Per quanto riguarda il **secondo commento** invece:

- > sintassi nome segnaposto: denominazione cliente - codice cliente - vincolo orario (Extra1) e l'indirizzo solo nel caso in cui lo abbia pescato da una diversa destinazione

    _Non dovrebbe essere un problema_

- > stile, colore, icona segnaposti, se possibile la stessa del kmz che già hai

    _Da vedere..._

- > sempre se possibile, che si "leghi" ad un altro kmz che abbia già di base i poligoni con le zone colorate, i CAP ecc. (questo dovrei provvedertelo)
    
    _Necessaria qualche informazione in più_

**Comment by lasorgentenet** [comment]
Considerando che l'xml da cui partiamo è quello della scheda ORDINI e non la rubrica, credo sia possibile che il KML sia creato a partire dagli indirizzi di consegna, giusto?

Ok per la sintassi. Per stile, colori ecc. va bene tutto...

Ti mando su WA il kmz da "mescolare" insieme a quello che tu farai uscire dal programma eventuale che farai.

**Comment by lasorgentenet** [comment]
Creato un kml ridotto all'osso (scremando col notepad tante cose inutili) con un solo segnaposto come input per te che ha il minimo di quello che ci serve. Codice cliente, nome e indirizzo. E funziona!

L'ho zippato altrimenti non lo faceva allegare.

[test.zip](https://github.com/LukeSavefrogs/danea-easyfatt/files/10813179/test.zip)

**Comment by lasorgentenet** [comment]
Ti facilito... dal defxml che esce da Danea, prendere questo per ogni cliente, esempio:

Questi vanno nel kml su "name":
<CustomerCode>11640</CustomerCode>
            <CustomerName>ATTIANI STEFANIA</CustomerName>

Questi vanno nel kml su "address":
      <CustomerAddress>VIA DI VILLA TAVERNA, 32</CustomerAddress>
      <CustomerPostcode>00078</CustomerPostcode>
      <CustomerCity>MONTE PORZIO CATONE</CustomerCity>

**Comment by lasorgentenet** [comment]
Possiamo amabilmente sollecitare questa richiesta? :)
Credo che sia una cosa very very easy considerando le altre fatte.
Ora che abbiamo una barca di ordini da evadere, il flag manuale su Earth ha il rischio errore dietro l'angolo hahah

**Comment by LukeSavefrogs** [comment]
> Possiamo amabilmente sollecitare questa richiesta? :)

Vedo che riesco a fare, purtroppo il tempo che ho è sempre lo stesso mentre le cose da fare aumentano ogni giorno 😁

**Comment by lasorgentenet** [comment]
Grandeee lo apprezziamo.
Se apri con notepad il test che ti ho fatto di eventuale file di uscita, è
veramente una bazzecola.
Andrea
*Servizio clienti - **LaSorgente.net*
<https://www.lasorgente.net/>
La Sorgente distribuzione S.r.l.
Web: LaSorgente.net <http://lasorgente.net/> | WhatsApp: 333 79 222 55
<https://api.whatsapp.com/send?phone=393337922255> | @
***@***.*** | Tel. 06 94 12649 <callto://+39069412649>


Il giorno lun 26 giu 2023 alle ore 15:56 Luca Salvarani <
***@***.***> ha scritto:

**Comment by LukeSavefrogs** [comment]
1. Scarica ed estrai questo zip sul Desktop del PC dove usi Easyfatt
2. Copia il database usato da Easyfatt (dovrebbe essere sotto `C:\Users\lucas\Documents\Danea Easyfatt\{nome-file}.eft`) e incollalo sempre sul Desktop
3. [Apri una finestra Powershell sul desktop](https://www.repairwin.com/how-to-open-powershell-as-administrator-at-current-folder-in-file-explorer-windows-10/) e lancia il programma estratto al punto 1.
4. Fai uno **screenshot** dell'output dello script e incollalo come **risposta a questo messaggio**.
5. Lo script avrà generato sul Desktop un file chiamato `test.kml`.
6. Apri una nuova finestra di Google Earth e **apri il file salvato al punto 5** (_File > Apri..._)
7. Il risultato dovrebbe essere simile al seguente (_ovviamente con i dati cliente corretti..._)
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/779aec98-eef8-46ea-8c1b-06d726ca9011)


[process_kml.zip](https://github.com/LukeSavefrogs/danea-easyfatt/files/11884246/process_kml.zip)

**Comment by LukeSavefrogs** [comment]
## **Riassunto call**

### Test script `process_xml.exe`
#### Problema
Inizialmente lanciando il comando `.\process_kml.exe '\\IP_ADDRESS\C$\Users\USERNAME\Documents\Danea Easyfatt\Archivi\ARCHIVE_NAME.eft'` lo script falliva con exception:

```python
OSError: [WinError 1326] Nome utente o password non corretta
```

#### Soluzione
Il problema si è risolto con i seguenti step:
1. Aprire "**Esplora file**"
2. Nella **barra degli indirizzi** inserire `\\IP_ADDRESS\C$\Users\USERNAME\Documents\Danea Easyfatt\Archivi\ARCHIVE_NAME.eft` (adattando dove necessario) e premere <kbd>INVIO</kbd>: Windows chiederà username e password
3. Chiedere all'amministratore del server di **inserire username e password** corretti e **salvare le credenziali** per quel percorso (in modo che al prossimo accesso Windows non le chieda più)

**Comment by lasorgentenet** [comment]
*** IMPORTANTE ***
Poiché nella schermata ordini cliente abbiamo dei "non-ordini", ovvero ordini da mettere in consegna non a stretto giro, ma solo quando il cliente ordinerà di nuovo (es. portare 1 bottiglia in più la prossima volta perché rotta, oppure fare questo sconto ecc.), vorremmo che non finissero nel kml degli ordini da evadere.

In commento uso interno abbiamo scritto ALTRO su questi "non-ordini", potresti fare in modo che non vengano considerati in esportazione per il kml?
Grazie.

**Comment by lasorgentenet** [comment]
Abbiamo deciso di provare ad utilizzarlo.
Il tempo che impiega Earth per aprire il kml è più o meno lo stesso che impieghiamo per fare il check manuale degli ordini in coda.

Alcune cose:
- Possibilmente solo prima lettera maiuscola e per il nome cliente fermarsi al primo spazio (es. solo cognome), altrimenti la mappa diventa un'accozzaglia di caratteri incomprensibile
- Possibilità di usare un'icona diversa, se hai messo il furgoncino, forse sei in grado di impostarne un'altra?

Abbiamo poi notato che il cliente che ha un ordine in coda è ripetuto due volte nell'elenco, una col flag una senza, non so se sia un bug.

Grazie!

**Comment by lasorgentenet** [comment]
Sì, abbiamo afferrato il problema relativo al **punto 1**.
La lentezza al momento è un aspetto secondario.

Il **punto 2**, se dici che non ci si mette assolutamente nulla, ottimo!
Ci permette di utilizzarlo.
Avviso anche in azienda di questa esigenza ;)

Il segnaposto sarebbe questo: http://maps.google.com/mapfiles/kml/paddle/red-circle.png
Scala 1,0 e opacità 100%.

**Punto 3**, risolvilo senza fretta.

Grazie mille a te!

**Comment by LukeSavefrogs** [comment]
Ho provato a fare quanto richiesto e ho rilasciato la [v1.2.2](https://github.com/LukeSavefrogs/danea-easyfatt/releases/tag/v1.2.2).

Per quanto riguarda il punto 2 ho fatto quello che potevo: dato che non ho accesso a nome e cognome separati ho impostato una lunghezza massima di 10 caratteri.

Come servizio di Geocoding invece ho usato Google Maps per 2 motivi:
- E' il più affidabile tra quelli che ho visionato
- E' lo stesso motore che usa Google Earth

Purtroppo **non è possibile** usare questa funzionalità senza prima aver generato la chiave API dalla console di Google Cloud 😅

Di seguito una guida sicuramente non completa ma il più chiara possibile che ho fatto per aiutare passo dopo passo:

**Prerequisiti**:
- Un account Google aziendale (volendo è possibile farlo anche con uno personale ma io consiglio caldamente di evitare)
- Una carta di credito (o una carta abilitata all'e-commerce)

## 1) Attivazione dell'account "Google Cloud"
1. Loggati con l'account Google dell'azienda e vai alla [Console Cloud Google](https://console.cloud.google.com/welcome?authuser=1) e clicca sul pulsante "Inizia gratuitamente" in alto a destra.
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/378cc994-c6a2-4514-8eca-ac5d4575fb6c)

2. Procedi con gli step richiesti inserendo anche Partita IVA e una carta di credito valida (NON verrà addebitato nulla, nè verrà automaticamente attivato il piano Business) che servirà nel malaugurato caso in cui dovessimo superare la soglia di richieste gratuite mensili (sono circa 30.000, quindi contando una per indirizzo cliente direi più che abbastanza)
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/58a19cbe-7a9d-40bd-bcfb-ca834fbf02bd)
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/8f2556bb-5f3d-4610-a979-da529adf4cf6)

3. Clicca su "Avvia la mia prova gratuita"
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/f84d157a-01d2-4cf2-8d17-a6151cf1c873)

4. Verifica la tua identità con una transazione finta sulla carta scelta (0,00€)
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/468d083d-090f-40b9-baa4-7cb053b6b052)


## 2) Creazione del progetto `Easyfatt`
1. Torna nella Dashboard e clicca sul menu a tendina in alto a destra (dovrebbe esserci scritto `My First Project`).
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/37981404-56fa-4bdd-8bab-392e352b783d)
2. Nel dialog che si aprà cliccare su "Nuovo progetto" in alto a destra
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/fb795eb9-3761-4558-a3e5-aaff5e9d3b59)
3. Scrivere `Easyfatt` (o qualsiasi altra cosa, è un nome che servirà a noi unicamente per riconoscere su cosa stiamo lavorando) nel campo del nome e premere "Crea"
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/ad1f8cdc-48c0-4116-af41-e197def324af)
6. Attendere che il progetto venga creato
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/febc0ed1-952e-42fe-bd5a-0d15db3c6bb0)
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/4d1e1b20-c5de-4b27-9a64-fe8238cfac6d)

7. Ora ripeti lo step 2.1 e nel dialog che si apre seleziona il progetto che hai creato allo step 2.3 e poi clicca su "Apri"
![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/1cc0d57a-3980-44c6-8b25-e67d558ec472)

8. In alto a sinistra ora dovresti vedere il tuo nuovo progetto attivo (invece del default `My First Project`)
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/09cf20eb-b94e-489d-8e68-13813b65fedc)

## 3) Attivazione del servizio di Geocoding

1. Nel campo di ricerca globale in alto al centro scrivi `Marketplace` e seleziona il risultato che vedi nello screenshot (dovrebbe essere il primo risultato):
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/bb57d516-54c3-4984-bfa4-8583840780d7)
2. Ora sei nel marketplace! Da qui possiamo attivare i servizi che ci interessano. Prova a cercare `Geocoding` (dovrebbe suggerirti automaticamente il servizio corretto, altrimenti premi semplicemente <kbd>INVIO</kbd>)
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/8a125b76-e300-4199-a59a-d5d92d29c4d9)
3. Dalla lista di servizi disponibili clicca su `Geocoding API` (dovrebbe essere il primo risultato come nel mio caso)
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/681cbfd5-74bb-4b61-908c-02c023777682)
4. Ora clicca su `Abilita`
    ![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/f9a9d55f-a297-40dc-8183-96b325c4538f)
5. Se hai saltato il punto 1 (_Attivazione dell'account_) ti chiederà di farlo ora per poter procedere.

**Comment by LukeSavefrogs** [comment]
Piccolo appunto: 
Dai miei test ho visto che al momento (usando `pickle` per serializzare istanze della classe `geopy.location.Location`) è stato generato un file di **178KB** a partire da un dataset di **166 indirizzi** (divisi per 59 clienti/fornitori). 

Questo vuol dire che **in media** ogni indirizzo serializzato peserà **`1.07KB`** (`1.1KB` se arrotondiamo per eccesso).

Domani bisogna provare a vedere qual'è un carico realistico da parte vostra per determinare in media quale possa essere la dimensione media di un file di cache (e se quindi è fattibile o bisogna ridimensionarlo togliendo le cose non necessarie).

**Comment by lasorgentenet** [comment]
Tutto FANTASTICO, 12-13 anni di lavoro manuale risolti.

Alcune piccole modifiche, senza fretta poiché è già utilizzabile così:
- lunghezza caratteri da 10 a 13
- solo prima lettera maiuscola
- clienti in ordine di nome anziché in ordine di codice cliente
- salvataggio file nella root del software, nome "Ordini in corso"

**Comment by LukeSavefrogs** [comment]
# ✨Release [`v1.3.1`](https://github.com/LukeSavefrogs/danea-easyfatt/releases/tag/v1.3.1) rilasciata
In questa release ho introdotto la possibilità di personalizzare ancora più a fondo il template. In particolare:


- > * lunghezza caratteri da 10 a 13
   
   Basta usare nel template il comando di formattazione `{variabile:s->substring(0, 13)}` (o `10`, come preferite voi)

--- 


- > * solo prima lettera maiuscola
  
  Basta usare nel template il comando di formattazione `{variabile:s->capitalize}` che fa esattamente questo

--- 

- > * salvataggio file nella root del software, nome "Ordini in corso"

  Adesso viene salvato di default nella stessa cartella del programma con il nome `output.kml`. Per personalizzare questa opzione è possibile modificare la [proprietà corrispondente nel file di configurazione](https://lukesavefrogs.github.io/danea-easyfatt/utente/configurazione.html#filesoutputkml)


## In sostanza...

- Per quanto riguarda la formattazione imposta la variabile di configurazione `features.kml_generation.placemark_title` come di seguito:
```toml
placemark_title = "{customerName:s->substring(0, 13)->capitalize} {customerCode}"
```
- Per quanto riguarda il nome con cui viene salvato il file se ti va bene `output.kml` lascia le cose così come stanno, altrimenti aggiungi la configurazione [`files.output.kml`](https://lukesavefrogs.github.io/danea-easyfatt/utente/configurazione.html#filesoutputkml) con il percorso e il nome del file desiderati.
- Ordine personalizzato ancora non disponibile

**Chiudo l'issue** in quanto la funzionalità è stata rilasciata e testata.

Per domande inerenti quanto detto continua a chiedere qui, altrimenti valutate di aprire nuovi Issue
