### ISSUE TITLE
Possibilità di apertura automatica del csv

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#20]
Sarebbe comodo se integration aprisse in automatico il file csv al termine della procedura.
O scegliendo un S o N al posto del tasto INVIO prima di chiudere il prompt, oppure scegliendo di farlo aprire o no dal file config.

**Comment by LukeSavefrogs** [comment]
Funzione introdotta a partire dalla versione **`1.0.0`**.

## Changelog
- [v1.0.0](https://github.com/LukeSavefrogs/danea-easyfatt/releases/tag/v1.0.0)
- [v1.0.1](https://github.com/LukeSavefrogs/danea-easyfatt/releases/tag/v1.0.1)
- [v1.0.2](https://github.com/LukeSavefrogs/danea-easyfatt/releases/tag/v1.0.2)
