### ISSUE TITLE
Orari di consegna per ogni consegna

### ISSUE THREAD

**Issue by LukeSavefrogs** [LukeSavefrogs/danea-easyfatt#5]
Al momento gli orari di consegna sono definiti **per cliente**.
L'obiettivo è fare in modo che sia possibile sovrascrivere quegli orari **ad ogni consegna**.

Ad esempio:
- Solitamente un cliente accetta consegne dalle 8 alle 12
- Per una consegna specifica richiede che sia consegnato tra le 10 e le 12

L'orario di consegna finale dovrebbe quindi essere `10>>12`

**Comment by lasorgentenet** [comment]
Può anche capitare l'inverso (anche se di rado), ovvero che un cliente che di solito ha un'esigenza particolare, per un dato ordine o giornata non la abbia, e a noi fa comodo perché possiamo andarci nell'orario che vogliamo. Suggerisco una stringa da mettere sempre in "commento uso interno" che annulli la lettura del vincolo in Extra1.

**Comment by LukeSavefrogs** [comment]
Valutare campo `CustomField1`

**Comment by lasorgentenet** [comment]
Ottima idea, approvato. Grazie.
CustomField1 quindi utilizzato per vincoli orari specifici di una data
consegna, e se presente annulla Extra1 che rappresenta invece un vincolo
orario permanente.
Andrea
*Servizio clienti - **LaSorgente.net*
<https://www.lasorgente.net/>
La Sorgente distribuzione S.r.l.
Web: LaSorgente.net <http://lasorgente.net/> | WhatsApp: 333 79 222 55
<https://api.whatsapp.com/send?phone=393337922255> | @
***@***.*** | Tel. 06 94 12649 <callto://+39069412649>


Il giorno gio 20 apr 2023 alle ore 04:14 Luca Salvarani <
***@***.***> ha scritto:

**Comment by LukeSavefrogs** [comment]
> CustomField1 quindi utilizzato per vincoli orari specifici di una data consegna, e se presente annulla Extra1 che rappresenta invece un vincolo orario permanente. 

Il valore viene letto dal campo **`CustomField4`**. 

In ordine di precedenza (_1 "sovrascrive" 2, ecc.._):

1. Singolo ordine (`CustomField4`)
2. Profilo clienti (`ExtraField1` nel file `ExportClienti.xlsx`)
3. File di configurazione utente `*.config.toml`
3. Default (`07:00-16:00`)
