### ISSUE TITLE
Problema output csv

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#93]
Quando un cliente ha il carattere "&" all'interno del nome, il generatore aggiunge "amp;"

**Comment by LukeSavefrogs** [comment]
A me vengono salvati correttamente:

![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/159e4177-e9eb-48c3-aa8d-411a067b1a5a)

Potresti mandarmi un estratto del nome (cambiando dati sensibili con valori dummy tipo "Mario Rossi" ecc..) e del risultato su CSV?

**Comment by lasorgentenet** [comment]
Come non detto, l'inghippo lo crea RouteXL!
Sorry!
Aggiunge quei caratteri a casaccio dopo che gli faccio fare la
pianificazione.

Andrea
*Servizio clienti - **LaSorgente.net*
<https://www.lasorgente.net/>
La Sorgente distribuzione S.r.l.
Web: LaSorgente.net <http://lasorgente.net/> | WhatsApp: 333 79 222 55
<https://api.whatsapp.com/send?phone=393337922255> | @
***@***.*** | Tel. 06 94 12649 <callto://+39069412649>


Il giorno lun 4 set 2023 alle ore 13:35 Luca Salvarani <
***@***.***> ha scritto:

**Comment by LukeSavefrogs** [comment]
Confermo,
l'esportazione di RouteXL causa la trasformazione dei caratteri speciali nelle [rispettive entità HTML](https://developer.mozilla.org/en-US/docs/Glossary/Entity#reserved_characters).

![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/5dce723a-206c-4134-b303-ac147fa8592e)

Chiudo l'issue perchè non riguardante il programma.
