### ISSUE TITLE
Indirizzo La Sorgente non necessario nel csv + idea output

### ISSUE THREAD

**Issue by lasorgentenet** [LukeSavefrogs/danea-easyfatt#94]
Come da oggetto, abbiamo l'account di RouteXL con arrivo e destinazione già impostati.

IDEA: anziché creare il csv, il programma potrebbe mettere nella clipboard il contenuto del csv, così che l'unico step da fare è "incolla" dentro route?

**Comment by LukeSavefrogs** [comment]
> Come da oggetto, abbiamo l'account di RouteXL con arrivo e destinazione già impostati.

E' **già possibile** da diverso tempo semplicemente "sbiancando" il contenuto della configurazione `files.input.addition`. Ad esempio:

```toml
[files.input]
easyfatt = "./Documenti.DefXml"
addition = ""
```


> IDEA: anziché creare il csv, il programma potrebbe mettere nella clipboard il contenuto del csv, così che l'unico step da fare è "incolla" dentro route?

Fatto 😃

![image](https://github.com/LukeSavefrogs/danea-easyfatt/assets/33452387/ab6bef9c-f565-4819-8a8d-cea0c3ce6537)

La funzione verrà rilasciata nella prossima versione
